mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt: "testtoken"
            #jwt_provider: App\Mercure\JwtProvider
